about:
  home: https://github.com/pirovc/fgap
  license: MIT
  summary: "FGAP: an automated gap closing tool"
build:
  number: 0
  skip: True  # [osx]
  
package:
  name: fgap
  version: 1.8.1
source:
  # fn: FGAP_1_8_1_LINUX64b.tar.gz
  # url: https://sourceforge.net/projects/fgap/files/FGAP_1_8_1_LINUX64b.tar.gz
  # sha256: 12d824390efddeff5c92c7ea1b191303e46dd9f6b34f2c858a747aaf00f986ef
  git_url: https://github.com/pirovc/fgap.git

requirements:
  run:
    - octave
    - blast
test:
  commands:
    - FGAP -h
