{% set version = "0.1.2.5" %}
{% set sha256 = "6d0f8d6741dea7359bb03b72258b42b52cb2af8a609f6688e557c0b32ac528de" %}

package:
  name: ococo
  version: {{ version }}

build:
  number: 0

source:
  fn:  ococo-{{ version }}.tar.gz
  url: https://github.com/karel-brinda/ococo/archive/ococo-{{ version }}.tar.gz
  sha256:  {{ sha256 }}

requirements:
  build:
    - gcc   # [not osx]
    - llvm  # [osx]
    - zlib ==1.2.8
    - libgcc # [not osx]

  run:
    - zlib ==1.2.8
    - libgcc  # [not osx]

test:
  commands:
    - ococo -v

about:
  home: http://github.com/karel-brinda/ococo
  license: MIT
  summary: Ococo, the first online consensus caller.
