{% set version = "1.4.0" %}
{% set name = "flowPloidy" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 5801bdc84ce29ddafd85eb8b6698fe3efbdbaabcf3a44c1220ac6f90df9372d1

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - bioconductor-flowcore
    - r-base
    - r-car
    - r-catools
    - r-knitr
    - r-minpack.lm
    - r-rmarkdown
    - r-shiny
  run:
    - bioconductor-flowcore
    - r-base
    - r-car
    - r-catools
    - r-knitr
    - r-minpack.lm
    - r-rmarkdown
    - r-shiny

test:
  commands:
    - '$R -e "library(''{{ name }}'')"'

about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Determine sample ploidy via flow cytometry histogram analysis. Reads Flow Cytometry Standard (FCS) files via the flowCore bioconductor package, and provides functions for determining the DNA ploidy of samples based on internal standards.'
