{% set name = "flashlfq" %}
{% set version = "0.1.100" %}

source:
    fn: FlashLFQ.zip
    url: https://github.com/smith-chem-wisc/FlashLFQ/releases/download/{{ version }}/FlashLFQ.zip
    sha256: a09d654423b771e09cf897b9488d1c5853daaf1cf5b44ed8c43fba4d70f02de4

package:
    name: {{ name }}
    version: {{ version }}

build:
  number: 0

requirements:
  build:
  run:
    - mono >=4.0.0

test:
    commands:
      - echo "" | FlashLFQ 2>1 | grep idt

about:
    home: https://github.com/smith-chem-wisc/FlashLFQ
    license: GLPL
    summary: ultrafast label-free quantification algorithm for mass-spectrometry proteomics
