{% set version = "4.1.1" %}

package:
  name: shapeit4
  version: {{ version }}

source:
  git_url: git@github.com:odelaneau/shapeit4.git
  git_rev: 910d28a3661646c31a766ce5147601e469eab28d

build:
  skip: True # [osx]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - boost-cpp
    - bzip2
    - htslib
  run:
    - boost-cpp
    - bzip2
    - htslib

test:
  commands:
    - shapeit4 --help

about:
  home: https://odelaneau.github.io/shapeit4/
  license: MIT
  license_file: LICENSE
  summary: fast and accurate method for estimation of haplotypes (phasing)

extra:
  identifiers:
    - doi:10.1101/493403
